### ISSUE TITLE
Disabled incompatible plug-in modules

### ISSUE THREAD

**Issue by Vin073** [altstoreio/AltStore#1193]
Disabled incompatible plug-in modules

The following plug-ins have been deactivated for "Mail":

AltPlugin.mailbundle

Please contact the manufacturers of these plug-ins to obtain a version compatible with Mail 16.0.

Computer: macbook 2020
System Version: 13.3 (22E252)

Mobile device: ipnone 14 pro max
System version: iOS 16.4

**Comment by ceeyang** [comment]
The same problem...

**Comment by Torrekie** [comment]
Find a solvet

1. Uninstall Mail Plugin
2. Open Terminal.app, try `sudo rm -rf ~/Library/Application\ Support/Mail/Plug-ins/Bundles` first, if no warnings then go step 8, otherwise if you see any warnings like `Operation not permitted` then continue the steps
3. Go Recovery mode, open Terminal
4. `ls /Volumes` and find your data disk (After macOS 10.15), mine is `/Volumes/Macintosh HD - Data`, then cd into it (e.g. `cd "/Volumes/Macintosh HD - Data"`)
5. Change to your user's home directory like `cd Users/torrekie`, depending on your username
6. Then try `rm -rf Library/Application\ Support/Mail/Plug-ins/Bundles`, this step is just same as step 2 but run as Recovery, it should able to modify or delete the file that you have seen the warning before
7. Reboot
8. Open AltServer and install Mail Plugin again

**Comment by Vin073** [comment]
> Find a solvet
> 
> 1. Uninstall Mail Plugin
> 2. Open Terminal.app, try `sudo rm -rf ~/Library/Application\ Support/Mail/Plug-ins/Bundles` first, if no warnings then go step 8, otherwise if you see any warnings like `Operation not permitted` then continue the steps
> 3. Go Recovery mode, open Terminal
> 4. `ls /Volumes` and find your data disk (After macOS 10.15), mine is `/Volumes/Macintosh HD - Data`, then cd into it (e.g. `cd "/Volumes/Macintosh HD - Data"`)
> 5. Change to your user's home directory like `cd Users/torrekie`, depending on your username
> 6. Then try `rm -rf Library/Application\ Support/Mail/Plug-ins/Bundles`, this step is just same as step 2 but run as Recovery, it should able to modify or delete the file that you have seen the warning before
> 7. Reboot
> 8. Open AltServer and install Mail Plugin again

When I execute step 5 through Recovery mode, I don't see the username folder, only the share folder
But in Finder I can see the username folder

**Comment by GhostIsBeHere** [comment]
> When I execute step 5 through Recovery mode, I don't see the username folder, only the share folder When entering username, a prompt that the directory cannot be found pops up
I also had this problem, and here's how I solved it:

1. Uninstall Mail Plugin
2. Boot into Recovery mode & open Terminal
3. Disable System Integrity Protection with `csrutil disable`
4. Restart
5. Open Terminal and run `sudo rm -r ~/Library/Application\ Support/Mail/Plug-ins/Bundles`
6. Reinstall Mail plugin
7. Open Mail and enable plugin
8. Restart Mail
9. Boot into Recovery mode & open Terminal
10. Re-enable System Integrity Protection with `csrutil enable`
11. Restart

**Comment by yinyu985** [comment]
Which files had a very deep path, first into /volume/ then Macintosh HD - Data then /User/youusername/Library/Application\ Support/Mail/Plug-ins/Bundles My problem was solved smoothly, delete and reinstall.
